[theme]

# Primary accent for interactive elements
primaryColor="#950740"

# Background color for the main content area
backgroundColor="#1a1a1d"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor="#950740"

# Color used for almost all text
textColor="#ffffff"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font="monospace"